# Generated by Django 2.2.12 on 2020-04-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0002_auto_20200423_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lessons',
        ),
        migrations.AddField(
            model_name='lesson',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collections_topics', to='giza.Collection'),
        ),
    ]
