# Generated by Django 3.2.9 on 2021-12-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0003_auto_20211217_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='picture',
            field=models.ImageField(blank=True, default='/images/default.png', upload_to='images'),
        ),
    ]
