# Generated by Django 2.2.12 on 2021-03-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0003_auto_20200423_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
