# Generated by Django 2.2.12 on 2021-03-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0004_lesson_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='items',
        ),
        migrations.CreateModel(
            name='ElasticsearchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('es_id', models.IntegerField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='giza.Collection')),
            ],
        ),
    ]
