# Generated by Django 2.2.12 on 2021-03-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0005_auto_20210314_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticsearchVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_id', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='giza.Lesson')),
            ],
        ),
    ]
