# Generated by Django 2.2.12 on 2021-04-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0005_auto_20210314_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
