# Generated by Django 2.2.24 on 2021-11-09 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0006_collection_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.TextField()),
                ('search', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
