# Generated by Django 2.2.24 on 2021-11-09 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0007_auto_20211109_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
