# Generated by Django 2.2.24 on 2021-11-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0008_auto_20211109_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
