# Generated by Django 2.2.24 on 2021-11-09 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('giza', '0009_delete_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.TextField()),
                ('search', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
