FROM python:3.10-slim-buster as python-build
WORKDIR /app
RUN apt-get update --fix-missing
# g++ for Pillow; unixodbc-dev for pyodbc
RUN apt-get install -y nginx python-psycopg2 postgresql graphviz gettext gdal-bin python-gdal python3-numpy gnupg gpg libpq-dev gcc g++ unixodbc-dev

# Nginx tweaked
RUN addgroup --system nginx
RUN adduser --system nginx
RUN usermod -a -G nginx nginx
RUN mkdir -p /run/nginx

RUN mkdir -p /var/log/nginx && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stdout /var/log/nginx/error.log

# Use dev NGINX config
# Nginx and Gunicorn are used if TEST_SERVER=False or is not set 
COPY nginx/nginx.dev.conf /etc/nginx/nginx.conf

# Python requirements
COPY requirements.txt /app
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1
ENV MIGRATE 0

EXPOSE 8000 5000

# volume is being mounted for Docker Compose but still need the entrypoint available and executable here
COPY docker/entrypoint /app/docker/entrypoint
RUN sed -i 's/\r$//g' /app/docker/entrypoint
RUN chmod +x /app/docker/entrypoint
CMD /app/docker/entrypoint